"""empty message

Revision ID: 9a249cfca24c
Revises: fadd0e1537df
Create Date: 2017-05-06 22:14:46.823855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a249cfca24c'
down_revision = 'fadd0e1537df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'summary')
    # ### end Alembic commands ###
